=== Elvira17477/KalenderApp_Praktikum/src/kalender/xml_files/kalender.xsd
<?xml version="1.0" encoding="UTF-8"?>                  <!-- prolog mit xml version & zeichenkodierung des docs -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">             <!-- Vorlage für Dokumente aus dem targetNamespace,
                                                             InstanzDocs müssen sich an Struktur und Typen des schemas halten -->

    <!-- Abstrakte Definition, besteht aus einem Namen und Liste von Terminen, dient als Basis für instanziierbare Kalender -->
    <!-- complexType: made of several elements -->
    <xs:complexType name = "Kalender" abstract="true">   <!-- abstract verhindert direkte Instanziierung -->
        <xs:sequence>            <!-- sequence legt Reihenfolge der elemente fest und verhindert zusätzliche elemente -->
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Termine">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Termin" type="Termin" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- complexType legt struktur und reihenfolge der attribute und kindelemente fest -->

    <!-- Wurzelelement Kalender, kann entweder Raum-, Personen- oder Gruppenkalender sein -->
    <xs:element name="Kalender">    <!-- simpleType kann nur textcontent enthalten, keine attribute oder kindelemente -->
        <xs:complexType>            <!-- complexType kann attribute, elemente oder oder einen mix davon enthalten -->
            <xs:choice>             <!-- choice beschränkt auf einen einzigen KalenderTyp innerhalb von Kalender -->
                <xs:element name="RaumKalender" type="RaumKalender"/>
                <xs:element name="PersonenKalender" type="PersonenKalender"/>
                <xs:element name="GruppenKalender" type="GruppenKalender"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>


    <!-- Definition RaumKalender, erweitert abstrakten KalenderTyp um das Element Plätze -->
    <xs:complexType name="RaumKalender">
        <xs:complexContent>     <!-- complexContent: Raumkalender extends Kalender und erbt alle elemente und attribute -->
            <xs:extension base="Kalender">
                <xs:sequence>
                    <xs:element name="Plaetze" type="xs:int"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <!-- Definition PersonenKalender, erweitert abstrakten KalenderTyp um das Element Besitzer -->
    <xs:complexType name="PersonenKalender">
        <xs:complexContent>
            <xs:extension base="Kalender">
                <xs:sequence>
                    <xs:element name="Besitzer" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <!-- Definition GruppenKalender, erweitert abstrakten KalenderTyp um eine Liste von bis zu 10 Mitglied-Elementen -->
    <xs:complexType name="GruppenKalender">
        <xs:complexContent>
            <xs:extension base="Kalender">
                <xs:sequence>
                    <xs:element name="Mitglieder">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="Mitglied" type="xs:string" maxOccurs="10"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <!-- Definition Termin -->
    <xs:complexType name="Termin">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Start" type="xs:dateTime"/>
            <xs:element name="Ende" type="xs:dateTime"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Elvira17477/KalenderApp_Praktikum/src/kalender/xml_files/RaumKalender1.xml
<?xml version="1.0" encoding="UTF-8"?>

<Kalender xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="kalender.xsd">
    <RaumKalender>
        <Name>Hörsaal D250</Name>
        <Termine>
            <Termin>
                <Name>Vorlesung Mathe2</Name>
                <Start>2024-05-30T08:00:00</Start>
                <Ende>2024-05-30T10:00:00</Ende>
            </Termin>
            <Termin>
                <Name>Vorlesung EIDOP</Name>
                <Start>2024-05-30T10:00:00</Start>
                <Ende>2024-05-30T12:00:00</Ende>
            </Termin>
            <Termin>
                <Name>Uebung Mathe2</Name>
                <Start>2024-05-30T12:00:00</Start>
                <Ende>2024-05-30T14:00:00</Ende>
            </Termin>
        </Termine>
        <Plaetze>400</Plaetze>
    </RaumKalender>
</Kalender>

=== Elvira17477/KalenderApp_Praktikum/src/kalender/xml_files/GruppenKalender2.xml
<?xml version="1.0" encoding="UTF-8"?>

<Kalender xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="kalender.xsd">
    <GruppenKalender>
        <Name>Gruppe2</Name>
        <Termine>
            <Termin>
                <Name>Praktikum EIDOP</Name>
                <Start>2024-05-30T08:00:00</Start>
                <Ende>2024-05-30T10:00:00</Ende>
            </Termin>
            <Termin>
                <Name>Praktikum EIDOP</Name>
                <Start>2024-06-06T08:00:00</Start>
                <Ende>2024-06-06T10:00:00</Ende>
            </Termin>
            <Termin>
                <Name>Praktikum EIDOP</Name>
                <Start>2024-06-13T08:00:00</Start>
                <Ende>2024-06-13T10:00:00</Ende>
            </Termin>
        </Termine>
        <Mitglieder>
            <Mitglied>Klara</Mitglied>
        </Mitglieder>
    </GruppenKalender>
</Kalender>

=== Elvira17477/KalenderApp_Praktikum/src/kalender/xml_files/PersonenKalender1.xml
<?xml version="1.0" encoding="UTF-8"?>

<Kalender xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="kalender.xsd">
    <PersonenKalender>
        <Name>Person1</Name>
        <Termine>
            <Termin>
                <Name>Zahnarzt</Name>
                <Start>2024-05-30T08:00:00</Start>
                <Ende>2024-05-30T09:00:00</Ende>
            </Termin>
            <Termin>
                <Name>Vorlesung Mathe</Name>
                <Start>2024-05-30T10:00:00</Start>
                <Ende>2024-05-30T12:00:00</Ende>
            </Termin>
            <Termin>
                <Name>Klettern</Name>
                <Start>2024-05-30T17:00:00</Start>
                <Ende>2024-05-30T19:00:00</Ende>
            </Termin>
        </Termine>
        <Besitzer>Eva</Besitzer>
    </PersonenKalender>
</Kalender>

=== Elvira17477/KalenderApp_Praktikum/src/kalender/xml_files/GruppenKalender1.xml
<?xml version="1.0" encoding="UTF-8"?>

<Kalender xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="kalender.xsd">
    <GruppenKalender>
        <Name>Gruppe1</Name>
        <Termine>
            <Termin>
                <Name>Praktikum KI</Name>
                <Start>2024-05-30T08:00:00</Start>
                <Ende>2024-05-30T12:00:00</Ende>
            </Termin>
            <Termin>
                <Name>Praktikum KI</Name>
                <Start>2024-06-06T08:00:00</Start>
                <Ende>2024-06-06T12:00:00</Ende>
            </Termin>
            <Termin>
                <Name>Praktikum KI</Name>
                <Start>2024-06-13T08:00:00</Start>
                <Ende>2024-06-13T12:00:00</Ende>
            </Termin>
        </Termine>
        <Mitglieder>
            <Mitglied>Martina</Mitglied>
            <Mitglied>Ella</Mitglied>
        </Mitglieder>
    </GruppenKalender>
</Kalender>
